[package]
name = "oath-authenticator"
version = "0.2.0"
authors = ["Nicolas Stalder <n@stalder.io>", "Szczepan Zalega <szczepan@nitrokey.com>"]
repository = "https://github.com/trussed-dev/oath-authenticator"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "OATH authenticator Trussed app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apdu-dispatch = { version = "0.1",  optional = true }
delog = "0.1.2"
flexiber = { version = "0.1.0", features = ["derive", "heapless"] }
heapless = "0.7"
heapless-bytes = "0.3"
hex-literal = "0.3"
interchange = "0.2"
iso7816 = "0.1"
serde = { version = "1", default-features = false }
trussed = "0.1.0"

# ctaphid
ctaphid-dispatch = { version = "0.1", optional = true }
usbd-ctaphid = { git = "https://github.com/Nitrokey/nitrokey-3-firmware", optional = true }

[dev-dependencies]
log = { version = "0.4.14", default-features = false }
clap = { version = "3.0.0", features = ["derive"] }
clap-num = "1.0.0"
pretty_env_logger = "0.4.0"


[features]
default = ["apdu-dispatch"]
ctaphid = ["ctaphid-dispatch", "usbd-ctaphid"]

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

[[example]]
name = "usbip_simulation"
required-features = ["ctaphid"]


[patch.crates-io]
#trussed = { git = "https://github.com/trussed-dev/trussed" }
