[package]
name = "secrets-app"
version = "0.12.0"
authors = ["Nicolas Stalder <n@stalder.io>", "Szczepan Zalega <szczepan@nitrokey.com>"]
repository = "https://github.com/Nitrokey/trussed-secrets-app/"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "Secrets App - a Trussed app to manage OTP and Password Safe features of Nitrokey 3"

[dependencies]
apdu-dispatch = { version = "0.1.2",  optional = true }
ctaphid-dispatch = { version = "0.1", optional = true }
cbor-smol = "0.4"
delog = "0.1.6"
flexiber = { version = "0.1.0", features = ["derive", "heapless"] }
heapless = "0.7"
heapless-bytes = "0.3"
hex-literal = "0.3"
interchange = "0.2"
iso7816 = "0.1"
serde = { version = "1", default-features = false }
trussed = { version = "0.1", features = ["clients-3"] }
encrypted_container = { path = "components/encrypted_container" }
block-padding = "0.3.3"
bitflags = "2.3.1"

# extension
trussed-auth = "0.2.2"

[dev-dependencies]
log = { version = "0.4.14", default-features = false }
pretty_env_logger = "0.4.0"

# below are for running the usbip example
trussed-usbip = { version = "0.0.1", features = ["ctaphid"], default-features = false }
usbd-ctaphid = "0.1"
clap = { version = "3.0.0", features = ["cargo", "derive"] }
clap-num = "1.0.0"
delog = { version = "0.1.6", features = ["std-log"] }
fido-authenticator = "0.1.1"

admin-app = { version = "0.1", features = ["log-all"] }

[features]
default = ["apdu-dispatch"]
devel = ["apdu-dispatch", "log-all", "delog/std-log", "devel-counters"]

# Count accesses to the read-only and read-write persistence storage
devel-counters = []

# Allow to use application over CTAPHID interface
ctaphid = ["ctaphid-dispatch"]

# Enable challenge-response method (only authentication, does not encrypt data)
challenge-response-auth = []

# Enable oath calculate-all command
calculate-all = []

# Require delay after failed request as a brute-force protection for Reverese HOTP Verification
brute-force-delay = []


log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

[[example]]
name="usbip"
required-features = ["ctaphid", "devel"]


[patch.crates-io]
flexiber = { git = "https://github.com/Nitrokey/flexiber", tag = "0.1.1.nitrokey" }
trussed = { git = "https://github.com/sosthene-nitrokey/trussed.git", rev = "6f095e14b27bd58ab8fa56cf6c616266d92fbfb4" }
littlefs2 = { git =  "https://github.com/Nitrokey/littlefs2", tag = "v0.3.2-nitrokey-2" }
trussed-auth = { git = "https://github.com/trussed-dev/trussed-auth.git" , rev = "0ac8f49608d1b5dab6ee72abf5dca88fb4c9ecff" }
ctaphid-dispatch = { git = "https://github.com/sosthene-nitrokey/ctaphid-dispatch.git", rev = "a5a3696d7cf0665414cf57cdea384dbc8a157f33" }
usbd-ctaphid = { git = "https://github.com/trussed-dev/usbd-ctaphid.git", rev = "2a35535e80255043429267d8ea07c063e76b94ab"}
trussed-usbip = { git = "https://github.com/trussed-dev/pc-usbip-runner.git", rev = "ef1750e648bd36b28a80851eb8a6fb885db79932" }
fido-authenticator = { git = "https://github.com/Nitrokey/fido-authenticator.git", rev = "76d3d88b374658d96bd3fe8bb02775f954db11c3" }
admin-app = { git = "https://github.com/Nitrokey/admin-app.git", rev = "b885407aa59f43cbac949fe119e1af6323a7289b" }

