[package]
name = "oath-authenticator"
version = "0.10.0"
authors = ["Nicolas Stalder <n@stalder.io>", "Szczepan Zalega <szczepan@nitrokey.com>"]
repository = "https://github.com/trussed-dev/oath-authenticator"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "OATH authenticator Trussed app"

[dependencies]
apdu-dispatch = { version = "0.1.2",  optional = true }
ctaphid-dispatch = { version = "0.1", optional = true }
cbor-smol = "0.4"
delog = "0.1.6"
flexiber = { version = "0.1.0", features = ["derive", "heapless"] }
heapless = "0.7"
heapless-bytes = "0.3"
hex-literal = "0.3"
interchange = "0.2"
iso7816 = "0.1"
serde = { version = "1", default-features = false }
trussed = { version = "0.1", features = ["clients-3"] }
encrypted_container = { path = "components/encrypted_container" }

# extension
trussed-auth = "0.2.0"

[dev-dependencies]
log = { version = "0.4.14", default-features = false }
pretty_env_logger = "0.4.0"

# below are for running the usbip example
trussed-usbip = { git = "https://github.com/trussed-dev/pc-usbip-runner", default-features = false, features = ["ctaphid"], rev = "f3a680ca4c9a1411838ae0774f1713f79d4c2979" }
usbd-ctaphid = "0.1"
clap = { version = "3.0.0", features = ["cargo", "derive"] }
clap-num = "1.0.0"
delog = { version = "0.1.6", features = ["std-log"] }
fido-authenticator = { version = "0.1", features = ["dispatch", "log-all"] }
admin-app = { version = "0.1", features = ["log-all"] }

[features]
default = ["apdu-dispatch"]
devel = ["apdu-dispatch", "log-all", "delog/std-log", "devel-counters"]

# Count accesses to the read-only and read-write persistence storage
devel-counters = []

# Allow to use application over CTAPHID interface
ctaphid = ["ctaphid-dispatch"]

# Enable challenge-response method (only authentication, does not encrypt data)
challenge-response-auth = []

# Enable oath calculate-all command
calculate-all = []

# Require delay after failed request as a brute-force protection for Reverese HOTP Verification
brute-force-delay = []


log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

[[example]]
name="usbip"
required-features = ["ctaphid", "devel"]


[patch.crates-io]
flexiber = { git = "https://github.com/Nitrokey/flexiber", tag = "0.1.1.nitrokey" }
trussed = { git = "https://github.com/Nitrokey/trussed", rev = "52da9bb" }
littlefs2 = { git =  "https://github.com/Nitrokey/littlefs2", tag = "v0.3.2-nitrokey-2" }
trussed-auth = { git = "https://github.com/trussed-dev/trussed-auth/", rev = "6beabd125ea57e87bf642e18278fcc2ba224c50c" }